### ISSUE TITLE
Issues related to the description of region and box parameters

### ISSUE THREAD

**Issue by chenyqmy** [mdtanker/polartoolkit#180]
Hello, mdtanker:
In the documentation of polartoolkit, I noticed that you describe the region parameter in the format of [e, w, n, s]. For example, in the region_xy_to_ll function. However, I find that this region parameter should be in the format of [xmin, xmax, ymin, ymax], which is also the default -R option in GMT. I think in the EPSG:3031 coordinate system, the [e, w, n, s] format may not be the proper description, and it could be a bit confusing. Moreover, in GMT, the [W|E|S|N] format is the way to specify the region.
I wonder if there's a mistake in this, and I could be wrong. Your package is very useful. Thank you for your work.

**Comment by mdtanker** [comment]
Hi @chenyqmy thank you so much for opening an issue! I think you are correct, and that discussing the region boundaries in terms of min and max is clearer than as east, west, north, south. 

From my understanding of what you're saying, there isn't anything to change in the code, just in the documentation, correct? 

If you'd like to contribute, please let me know and I'm happy to help out! Not sure of your level of experience, but this would be a great entry-level issue to fix 😀 

No worries if not, I'm happy to implement this fix.

**Comment by chenyqmy** [comment]
Yes, they are just in documentations. From my experience with the code, the return value is right.

**Comment by chenyqmy** [comment]
I'm not very familiar with the open-source collaboration process, but I might still be able to help with the documentation.😊

**Comment by mdtanker** [comment]
No worries about not having experience, it's not as hard as it seems! If it's just documentation you're changing, it should be easy to do on GitHub only without needing to fork or anytbing, instructions should be [here](https://polartoolkit.readthedocs.io/en/latest/contributing.html#documentation). 

Or you can go through the typical contribution process. Have a look at the [contributing guide](https://polartoolkit.readthedocs.io/en/latest/contributing.html) for how to fork the package, make and activate your environment. Make you changes locally, run the style check commands with `make`, then push the changes to your forked repo and open a PR in the main repo.

Let me know if you have any questions or issues, as I think the contributing guide definitely could be better.
