### ISSUE TITLE
Plot viewing procedures differ in the Download Antarctica datasets tutorial

### ISSUE THREAD

**Issue by PennyHow** [mdtanker/polartoolkit#199]
**Description of the desired feature:** The [Download Antarctica datasets](https://polartoolkit.readthedocs.io/en/latest/tutorial/fetch_walkthrough.html) tutorial does not contain the same plotting procedure for viewing each of the generated figures (compared to the other tutorials). Shouldn't you need a figure priming function after `maps.plot_grd(grid)`? Perhaps something like this:

```python
maps.plot_grd(grid)
fig = maps.plot_grd(grid)
fig.show()
```

**Comment by mdtanker** [comment]
Good catch. It seems Jupyter notebooks will automatically show the figure either way, but to be compatible with running from the terminal, I will add in your correction as part of #195.
