### ISSUE TITLE
EarthDataDownloader object to retain user login credentials

### ISSUE THREAD

**Issue by PennyHow** [mdtanker/polartoolkit#200]
**Description of the desired feature:** Functionality added so that login credentials are retained by the `EarthDataDownloader` object after first inputted, and therefore the user does not have to keep re-defining them for each download. 

In the tutorials, there is repeated EarthData login requests. For example, in the [3D_stack tutorial](https://polartoolkit.readthedocs.io/en/latest/gallery/3D_stack.html#Add-a-shapefile-to-mask-the-grids,-and-fine-tune-the-layout): 

```
measures_shelves = fetch.measures_boundaries(version="IceShelf")
``` 

Also, there is nothing in your documentation on how to define credentials as environment variables (the icepack link in the [API reference for EarthDataDownloader](https://polartoolkit.readthedocs.io/en/latest/api/polartoolkit.fetch.html#polartoolkit.fetch.EarthDataDownloader) is broken).

**Comment by JessicaS11** [comment]
If you're not familiar with it, I strongly recommend [earthaccess](https://earthaccess.readthedocs.io/en/latest/). It's a great way to manage Earthdata logins. The library I maintain, [icepyx](https://github.com/icesat2py/icepyx/blob/development/icepyx/core/auth.py) has it set up as an authentication MixIn class so the credentials are accessible from any module that needs them but only asks users for them once.

**Comment by mdtanker** [comment]
Thanks for the suggestions! I had a look, but I'm not sure if this will work here. `polartoolkit` uses `pooch` to download the datasets. For the NASA data, `pooch` requires the earthdata username and password to be entered into the download call. Looking through earthaccess, I couldn't see a way to return the username and password values to pass to pooch. Maybe I missed it, is there  a way to do this? 

For now, I've kept it as is, but added better documentation for how to set temporarily or permanent environment variables so users don't need to continuously supply the login credentials.

**Comment by PennyHow** [comment]
> For now, I've kept it as is, but added better documentation for how to set temporarily or permanent environment variables so users don't need to continuously supply the login credentials.

I think as long as it is well documented then this is enough to resolve the issue

**Comment by mdtanker** [comment]
Ok that sounds good to me, I'll close this as I've added better documentation in #212 in [this how-to guide](https://polartoolkit.readthedocs.io/en/latest/how_to/download_NASA_data.html).

**Comment by JessicaS11** [comment]
> Looking through earthaccess, I couldn't see a way to return the username and password values to pass to pooch. Maybe I missed it, is there a way to do this?

It's not part of the user api (and probably not documented), but with an earthaccess Auth object (created with `myauth = earthaccess.login()`) you should be able to get them with [`myauth.auth_environ()`](https://github.com/nsidc/earthaccess/blob/9563af0cc8ad39ec676c286ec27c7adbb146059a/earthaccess/api.py#L364) (or possibly `myauth.auth.auth_environ()`).

As @PennyHow noted - not required for JOSS, but wanted to follow up and answer your question!

**Comment by mdtanker** [comment]
Ahh great! Thanks for finding that, this is working to access the credentials: `earthaccess.auth_environ()`.

I'll add this into PolarToolkit to replace the custom class I had.
