### ISSUE TITLE
Problems with the use of "plot_grd" function of the module "maps"

### ISSUE THREAD

**Issue by Bohr-niels** [mdtanker/polartoolkit#207]
Can the function "plot_grd" plot the area outside the Antarctic region?
 I want to plot the Beaufort Sea in the Arctic, but there are some problems with the projection of the map, the right map with a correct projection is like this:
<img width="409" alt="image" src="https://github.com/mdtanker/polartoolkit/assets/71837181/3d58a425-b47b-42c1-bfb9-6bde71eab6f3">
but now using the "plot_grd" I get the map below:
<img width="391" alt="image" src="https://github.com/mdtanker/polartoolkit/assets/71837181/3d1bcea6-5e34-4948-8bfd-aa9804f15142">
I think it should be the wrong projection setting, but the "plot_grd" function doesn't contain the projection parameter, and in the reference documentation I haven't found the relevant information yet.

**Comment by mdtanker** [comment]
Hi @Bohr-niels , that is a well timed question! I've just added support for plotting maps of the Arctic/Greenland. This is currently in PR #195, which will be released in the next few weeks, or you can clone the branch `mdtanker-patch-3` and install it locally. There should be some instructions for how to do that in the docs. Let me know if you need help.

Currently I only support plotting with either EPSG 3031, South Polar Stereographic (for antarctica, south of -60°), and EPSG 3413, Sea Ice Polar Stereogrpahic (for greenland and the arctic, north of 60°).

The projections for the figures are set with the function `utils.set_proj` which is called internally in `maps.plot_grd`. In the branch above, you must tell polartoolkit which of these projections you want to use with the keyword argument `hemisphere` with a value of "north" or "south", for whichever hemisphere you want. 

If your data is already in EPSG 3413, then plot_grd should work if you pass `hemisphere="north"`. If not, you'll need to reproject it, let me know if you need help with that.

**Comment by Bohr-niels** [comment]
Thanks a lot, @mdtanker. My data is geographic data in LLZ formats, so if I want to use plot_grd to map it, Should I first reproject it to XYZ formats using EPSG 3413? Maybe pygmt tool helps this work?

**Comment by mdtanker** [comment]
Yeah first reproject it. I use rioxarray to project from lat lon to meters, see [here](https://github.com/mdtanker/polartoolkit/blob/bc180cc62a9e1ba8eb0d0966add9afdb740e572b/src/polartoolkit/fetch.py#L1431C15-L1431C45) for an example or projecting to EPSG 3031. Should work to just replace 3031 with 3413.

**Comment by mdtanker** [comment]
Should be closed when #195 is merged.
